stages:
  clean:
    foreach:
      - dataset: poleval2019_cyberbullying
        datacleaner: LemmatizerSM
    do:
      cmd: python scripts/clean.py "${item.dataset}" "${item.datacleaner}"
      deps:
        - scripts/clean.py
        - data/${item.dataset}/raw
        - src/objects/datacleaners/${item.datacleaner}.py
        - src/objects/datacleaners/DataCleaner.py
      outs:
        - data/${item.dataset}/${item.datacleaner}
  
  vectorize:
    foreach:
      - dataset: poleval2019_cyberbullying
        datacleaner: LemmatizerSM
        vectorizer: CountVectorizer
    do:
      cmd: python scripts/vectorize.py "${item.dataset}" "${item.datacleaner}" "${item.vectorizer}"
      deps:
        - scripts/vectorize.py
        - data/${item.dataset}/${item.datacleaner}
        - src/objects/vectorizers/${item.vectorizer}.py
        - src/objects/vectorizers/Vectorizer.py
      outs:
        - data/${item.dataset}/${item.datacleaner}_${item.vectorizer}

  evaluate:
    foreach:
      - dataset: poleval2019_cyberbullying
        datacleaner: LemmatizerSM
        vectorizer: CountVectorizer
        model: SVC
    do:
      cmd: python scripts/evaluate.py "${item.dataset}" "${item.datacleaner}" "${item.vectorizer}" "${item.model}"
      deps:
        - scripts/evaluate.py
        - data/${item.dataset}/${item.datacleaner}_${item.vectorizer}
        - src/objects/models/Model.py
        - src/objects/models/${item.model}.py