stages:

  load:
    foreach: ${load}
    do:
      cmd:
        - echo data/${item.dataloader}/raw/test.parquet
        - python scripts/load.py "${item.dataloader}"
      deps:
        - scripts/load.py
        - datasets_raw/
        - stages/dataloaders/${item.dataloader}.py
        - imports_validator/load/${item.dataloader}.yaml
      outs:
        - data/${item.dataloader}/raw

  clean:
    foreach: ${clean}
    do:
      cmd:
        - python scripts/clean.py "${item.dataloader}" "${item.datacleaner}"
      deps:
        - scripts/clean.py
        - data/${item.dataloader}/raw
        - stages/datacleaners/${item.datacleaner}.py
        - imports_validator/clean/${item.datacleaner}.yaml
      outs:
        - data/${item.dataloader}/${item.datacleaner}

  vectorize:
    foreach: ${vectorize}
    do:
      cmd: python scripts/vectorize.py "${item.dataloader}" "${item.datacleaner}" "${item.vectorizer}"
      deps:
        - scripts/vectorize.py
        - data/${item.dataloader}/${item.datacleaner}
        - stages/vectorizers/${item.vectorizer}.py
        - imports_validator/vectorize/${item.vectorizer}.yaml
      outs:
        - data/${item.dataloader}/${item.datacleaner}_${item.vectorizer}

  merge:
    foreach: ${merge}
    do:
      cmd: python scripts/merge.py "${item.dataloader}" "${item.datacleaner}" "${item.vectorizer_A}" "${item.vectorizer_B}" "${item.vectorizer_name}"
      deps:
        - scripts/merge.py
        - data/${item.dataloader}/${item.datacleaner}_${item.vectorizer_A}
        - data/${item.dataloader}/${item.datacleaner}_${item.vectorizer_B}
        - stages/vectorizers/Vectorizer.py
        - stages/models/Model.py
        - stages/models/MergeModel.py
      outs:
        - data/${item.dataloader}/${item.datacleaner}_${item.vectorizer_name}

  evaluate_classification:
    matrix:
      data: ${evaluate_classification}
      model: ${classification_models}
    cmd: python scripts/evaluate.py "${item.data.dataloader}" "${item.data.datacleaner}" "${item.data.vectorizer}" "${item.model.model}" "${item.model.params}"
    deps:
      - scripts/evaluate.py
      - data/${item.data.dataloader}/${item.data.datacleaner}_${item.data.vectorizer}
      - stages/models/${item.model.model}.py
      - params/${item.model.params}.yaml
      - imports_validator/evaluate/${item.model.model}.yaml
    outs:
      - results/${item.data.dataloader}/${item.data.datacleaner}/${item.data.vectorizer}/${item.model.model}/${item.model.params}.json
      - mlruns_store/${item.data.dataloader}/${item.data.datacleaner}/${item.data.vectorizer}/${item.model.model}/${item.model.params}/out_mlflow.zip
  
  # Uncomment when there is a clustering task
  evaluate_clustering:
    matrix:
      data: ${evaluate_clustering}
      model: ${clustering_models}
    cmd: python scripts/evaluate.py "${item.data.dataloader}" "${item.data.datacleaner}" "${item.data.vectorizer}" "${item.model.model}" "${item.model.params}"
    deps:
      - scripts/evaluate.py
      - data/${item.data.dataloader}/${item.data.datacleaner}_${item.data.vectorizer}
      - stages/models/${item.model.model}.py
      - params/${item.model.params}.yaml
      - imports_validator/evaluate/${item.model.model}.yaml
    outs:
      - results/${item.data.dataloader}/${item.data.datacleaner}/${item.data.vectorizer}/${item.model.model}/${item.model.params}.json
      - mlruns_store/${item.data.dataloader}/${item.data.datacleaner}/${item.data.vectorizer}/${item.model.model}/${item.model.params}/out_mlflow.zip