load:
  - dataloader: DatasetXD

clean:
  - dataset: DatasetXD
    datacleaner: LemmatizerSM

vectorize:
  - dataset: DatasetXD
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer

evaluate:
  - dataset: DatasetXD
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer

models:
  - model: SVC_1
  - model: SVC_2
