load:
  - dataloader: RpTweets
  - dataloader: RpTweetsXS

clean:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization

vectorize:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer5000

evaluate:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer5000

models:
#  - model: SVC
#    params: SVC1
#  - model: SVC
#    params: SVC2
  - model: LogisticRegression
    params: LR1
