load:
  - dataloader: TweetsRp
  - dataloader: TweetsRpXS

clean:
  - dataset: TweetsRpXS
    datacleaner: LemmatizerSM

vectorize:
  - dataset: TweetsRpXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer

evaluate:
  - dataset: TweetsRpXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer

models:
  - model: SVC
    params: SVC1
  - model: SVC
    params: SVC2
