load:
  - dataloader: TweeterCyberbullying

clean:
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner

vectorize:
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: SpacyMorphTagVectorizer
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: CountVectorizer1000
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: DPEBPVectorizer100Avg
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: HerbertVectorizer
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: TfidfVectorizer1000

evaluate_classification:
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: SpacyMorphTagVectorizer
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: CountVectorizer1000
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: DPEBPVectorizer100Avg
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: HerbertVectorizer
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: TfidfVectorizer1000

evaluate_clustering:
  # TODO

classification_models:
  - model: RandomForest
    params: RandomForest1
  - model: MLP
    params: MLP1
  - model: LogisticRegression
    params: LR1
  - model: SVC
    params: SVC1

clustering_models:
  # TODO
