load:
  - dataloader: RpTweets
  - dataloader: RpTweetsXS

clean:
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization

vectorize:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer

evaluate:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer

models:
  - model: SVC
    params: SVC1
  - model: SVC
    params: SVC2
