load:
  - dataloader: TweeterCyberbullying

clean:
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner

vectorize:
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: SpacyMorphTagVectorizer
    tasks: classification
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: CountVectorizer1000
    tasks: classification
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: DPEBPVectorizer100Avg
    tasks: classification
  # - dataloader: TweeterCyberbullying
  #   datacleaner: DummyDatacleaner
  #   vectorizer: HerbertVectorizer
  #   tasks: classification
  - dataloader: TweeterCyberbullying
    datacleaner: DummyDatacleaner
    vectorizer: TfidfVectorizer1000
    tasks: classification

classification_models:
  - model: RandomForest
    params: RandomForest1
  - model: MLP
    params: MLP1
  - model: LogisticRegression
    params: LR1
  - model: SVC
    params: SVC1

# TODO fix this
clustering_models:
  - model: DummyClusteringModel
    params: DCM
