load:
  - dataloader: RpTweetsXS
  - dataloader: MsTweetsV2

clean:
  - dataloader: RpTweetsXS
    datacleaner: LemmatizerSM
  - dataloader: RpTweetsXS
    datacleaner: TweetNormalization
  - dataloader: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip

vectorize:
  - dataloader: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataloader: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer1000
  - dataloader: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataloader: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: CountVectorizer1000
  - dataloader: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: CountVectorizer5000
  - dataloader: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: TfidfVectorizer1000
  - dataloader: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: TfidfVectorizer5000


models:
  - model: SVC
    params: SVC1
  - model: SVC
    params: SVC2
  - model: SVC
    params: SVC3
  - model: MLP
    params: MLP1