load:
  - dataloader: RpTweets
  - dataloader: RpTweetsXS
  - dataloader: MsTweets
  - dataloader: MsTweetsV2

clean:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
  - dataset: RpTweets
    datacleaner: TweetNormalization
  - dataset: MsTweets
    datacleaner: TweetNormalization
  - dataset: MsTweets
    datacleaner: TweetNormalizationHashtagSkip
  # MsTweetsV2
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM

vectorize:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: TfidfVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: TfidfVectorizer5000
  # MsTweetsV2
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer5000
  # MsTweetsV2 TweetNormalizationHashtagSkip
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: CountVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: CountVectorizer5000
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: TfidfVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: TfidfVectorizer5000


evaluate:
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: CountVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: TfidfVectorizer1000
  - dataset: RpTweetsXS
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer5000
  - dataset: RpTweetsXS
    datacleaner: TweetNormalization
    vectorizer: TfidfVectorizer5000
  # MsTweetsV2 LemmatizerSM
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: CountVectorizer5000
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: LemmatizerSM
    vectorizer: TfidfVectorizer5000
  # MsTweetsV2 TweetNormalizationHashtagSkip
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: CountVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: CountVectorizer5000
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: TfidfVectorizer1000
  - dataset: MsTweetsV2
    datacleaner: TweetNormalizationHashtagSkip
    vectorizer: TfidfVectorizer5000


models:
#  - model: SVC
#    params: SVC1
#  - model: SVC
#    params: SVC2
  - model: SVC
    params: SVC3
  - model: LogisticRegression
    params: LR1
  - model: MLP
    params: MLP1
